// This file is generated by Slice Machine. Update with care!

import HeroSideBySide from './HeroSideBySide';

export {
	HeroSideBySide,
};

export const components = {
	hero_side_by_side: HeroSideBySide,
};
